In [ ]:
import pandas as pd
data = pd.read_csv("/kaggle/input/datasets/mohammadanalytics/da-netflix-python/Dataset_Netflix.csv")

## Basic Information about the Dataset

In [ ]:
# Top 5 resords of the datasset
data.head()

In [ ]:
# Bottom 5 resords of the datasset
data.tail()

In [ ]:
# No. of total Rows and Colums
data.shape

In [ ]:
# No. of total values(elements) in the dataset
data.size

In [ ]:
# Column Name
data.columns

In [ ]:
# Data-type of each column
data.dtypes

In [ ]:
# Showing indexes, colums, data-types of each column, memory at once
data.info()

## Data Cleaning

In [ ]:
# Find and remove duplicate records
data.head()
data.shape

In [ ]:
# Find the duplicate records
data[data.duplicated()]

In [ ]:
# Remove the duplicate records
data.drop_duplicates(inplace = True)

In [ ]:
data.shape

In [ ]:
# Check Null Value present in any column? 
data.isnull()

In [ ]:
# Count No. of Null values in each colums
data.isnull().sum()

In [ ]:
import seaborn as sns

In [ ]:
# Showing Null Values with Heat-map.
sns.heatmap(data.isnull())

## Problem Statement

In [ ]:
# Q. 1) For 'House of Cards', what is the Show Id and Who is the Director of this show ? 

    # find all records of a particular item in any column. (1st Option)
data[data['Title'].isin(['House of Cards'])]

In [ ]:
    # (2nd Option)
data[data['Title'].str.contains('House of Cards')]

In [ ]:
# Q. 2) In which year the highest number of the TV Shows & Movies were released ? Show with Bar Graph. 

data['Date_N'] = pd.to_datetime(
    data['Release_Date'].str.strip(),
    format="%B %d, %Y")

In [ ]:
data.dtypes

In [ ]:
    # Counts the dates of all individual years in "Date_N" column. 
data['Date_N'].dt.year.value_counts()

In [ ]:
# Create a Bar Graph 
data['Date_N'].dt.year.value_counts().plot(kind="bar")

In [ ]:
# Q. 3) How many Movies & TV Shows are in the dataset? Show with Bar Graph. 
    # Using Groupby()
data.groupby('Category').Category.count()

In [ ]:
sns.countplot(data['Category'])

In [ ]:
# Q. 4) Show all the Movies that were released in year 2000. 
    
    # Cretae new column "Year" and it will consider only Yaer. 
data['Year'] = data['Date_N'].dt.year

In [ ]:
    # Filtering 2 colums
data[(data['Category'] == 'Movie') & (data['Year'] == 2000)]

In [ ]:
# Q. 5) Show only the Titles of all TV Shows that were released in India only.

data[(data['Category'] =='TV Show') & (data['Country']=='India')] ['Title']

In [ ]:
# Q. 6) Show Top 10 Directors, who gave the highest number of TV Shows & Movies to Netflix?

data['Director'].value_counts().head(10)

In [ ]:
# Q. 7) Show all the Records, where "Category is Movie and Type is Comedies" or "Country is United Kingdom".

data[(data['Category']=='Movie') & (data['Type']=='Comedies')]

In [ ]:
data[(data['Category']=='Movie') & (data['Type']=='Comedies') | (data['Country']=='United Kingdom')]

In [ ]:
# Q. 8) In how many movies/shows, Tom Cruise was cast?

data[(data['Cast']=='Tom Cruise')]

In [ ]:
data[data['Cast'].str.contains('Tom Cruise')]

In [ ]:
    # drop the rows that contains all or any missing values. 
data_new=data.dropna()

In [ ]:
data_new[data_new['Cast'].str.contains('Tom Cruise')]

In [ ]:
# Q. 9) What are the different Ratings defined by Netflix ?   

data['Rating'].nunique()

In [ ]:
data['Rating'].unique()

In [ ]:
# Q. 9.1) How many Movies got the 'TV-14' rating, in Canada?

data[(data['Category']=='Movie') & (data['Rating']=='TV-14')].shape

In [ ]:
data[(data['Category']=='Movie') & (data['Rating']=='TV-14') & (data['Country']=='Canada')].shape

In [ ]:
# Q. 9.2) How many TV Shows got the 'R' rating, after year 2018?

data[(data['Category']=='TV Show') & (data['Rating']=='R')]

In [ ]:
data[(data['Category']=='TV Show') & (data['Rating']=='R') & (data['Year']>2018)]

In [ ]:
# Q. 10) What is the maximum duration of a Movie/Show on Netflix?

data.Duration.unique()

In [178]:
data.Duration.dtypes

dtype('O')

In [179]:
data[['Minutes','Unit']] = data['Duration'].str.split(' ', expand = True)

In [180]:
data['Minutes'].max()

'99'

In [182]:
# Q. 11) Which individual country has the Highest No. of TV Shows ? 

data_tvshow = data[data['Category'] == 'TV Show']

In [185]:
data_tvshow.Country.value_counts()

Country
United States                                    705
United Kingdom                                   204
Japan                                            157
South Korea                                      147
India                                             71
                                                ...
United Kingdom, Ireland, United States             1
United Kingdom, Spain                              1
Italy, United States                               1
Japan, Canada                                      1
United States, France, South Korea, Indonesia      1
Name: count, Length: 183, dtype: int64

In [186]:
data_tvshow.Country.value_counts().head(1)

Country
United States    705
Name: count, dtype: int64

In [191]:
# Q. 12) How can we sort the dataset by Year?

data.sort_values(by='Year', ascending = False).head(2)

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description,Date_N,Year,Minutes,Unit
6440,s6439,TV Show,The Haunted Hathaways,NaN,"Amber Frank, Curtis Harris, Benjamin Flores Jr...",United States,"January 1, 2021",TV-G,2 Seasons,"Kids' TV, TV Comedies, TV Sci-Fi & Fantasy",Single mom Michelle Hathaway and her daughters...,2021-01-01,2021.0,2,Seasons
6289,s6289,Movie,The Departed,Martin Scorsese,"Leonardo DiCaprio, Matt Damon, Jack Nicholson,...","United States, Hong Kong","January 1, 2021",R,151 min,"Dramas, Thrillers",Two rookie Boston cops are sent deep undercove...,2021-01-01,2021.0,151,min

In [194]:
# Q. 13) Find all the instances where: 

# Category is 'Movie' and Type is 'Dramas' or 
# Category is 'TV Show' & Type is 'Kids' TV'.

data[(data['Category'] == 'Movie') & (data['Type'] == 'Dramas')].head(2)

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description,Date_N,Year,Minutes,Unit
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",PG-13,123 min,Dramas,A brilliant group of students become card-coun...,2020-01-01,2020.0,123,min
7,s8,Movie,187,Kevin Reynolds,"Samuel L. Jackson, John Heard, Kelly Rowan, Cl...",United States,"November 1, 2019",R,119 min,Dramas,After one of his high school students attacks ...,2019-11-01,2019.0,119,min

In [197]:
data[(data['Category']=='TV Show') & (data['Type']== "Kids' TV")].head(2)

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description,Date_N,Year,Minutes,Unit
111,s112,TV Show,44 Cats,NaN,"Sarah Natochenny, Suzy Myers, Simona Berman, E...",Italy,"October 1, 2020",TV-Y7,2 Seasons,Kids' TV,Paw-esome tales abound when singing furry frie...,2020-10-01,2020.0,2,Seasons
276,s277,TV Show,Abby Hatcher,Kyran Kelly,"Macy Drouin, Wyatt White, Paul Sun-Hyung Lee, ...","United States, Canada","July 1, 2020",TV-Y,1 Season,Kids' TV,A big-hearted girl helps her Fuzzly friends wh...,2020-07-01,2020.0,1,Season

In [198]:
data[(data['Category'] == 'Movie') & (data['Type'] == 'Dramas') | (data['Category']=='TV Show') & (data['Type']== "Kids' TV")]

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description,Date_N,Year,Minutes,Unit
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",PG-13,123 min,Dramas,A brilliant group of students become card-coun...,2020-01-01,2020.0,123,min
7,s8,Movie,187,Kevin Reynolds,"Samuel L. Jackson, John Heard, Kelly Rowan, Cl...",United States,"November 1, 2019",R,119 min,Dramas,After one of his high school students attacks ...,2019-11-01,2019.0,119,min
111,s112,TV Show,44 Cats,NaN,"Sarah Natochenny, Suzy Myers, Simona Berman, E...",Italy,"October 1, 2020",TV-Y7,2 Seasons,Kids' TV,Paw-esome tales abound when singing furry frie...,2020-10-01,2020.0,2,Seasons
170,s171,Movie,A Family Man,Mark Williams,"Gerard Butler, Gretchen Mol, Alison Brie, Will...","Canada, United States","December 15, 2019",R,110 min,Dramas,A ruthless corporate headhunter battles his ri...,2019-12-15,2019.0,110,min
232,s233,Movie,A Stoning in Fulham County,Larry Elikann,"Ken Olin, Jill Eikenberry, Maureen Mueller, Gr...",United States,"October 1, 2011",TV-14,95 min,Dramas,"After reckless teens kill an Amish child, a pr...",2011-10-01,2011.0,95,min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7668,s7667,TV Show,World of Winx,Iginio Straffi,"Haven Paschall, Alysha Deslorieux, Jessica Paq...","Italy, United States","June 16, 2017",TV-Y7,2 Seasons,Kids' TV,"The reality show ""WOW!"" engages the Winx in th...",2017-06-16,2017.0,2,Seasons
7717,s7716,TV Show,Yoko,NaN,"Eileen Stevens, Alyson Leigh Rosenfeld, Sarah ...",NaN,"June 23, 2018",TV-Y,1 Season,Kids' TV,"Friends Mai, Oto and Vik's games at the park b...",2018-06-23,2018.0,1,Season
7719,s7718,TV Show,YOM,NaN,"Sairaj, Devyani Dagaonkar, Ketan Singh, Mayur ...",NaN,"June 7, 2018",TV-Y7,1 Season,Kids' TV,"With the mind of a human being, and the body o...",2018-06-07,2018.0,1,Season
7758,s7757,TV Show,Z4,NaN,"Apollo Costa, Gabriel Santana, Matheus Lustosa...",Brazil,"February 22, 2019",TV-PG,2 Seasons,Kids' TV,Fading music biz veteran Zé realizes he has ju...,2019-02-22,2019.0,2,Seasons
7761,s7760,TV Show,Zak Storm,NaN,"Michael Johnston, Jessica Gee-George, Christin...","United States, France, South Korea, Indonesia","September 13, 2018",TV-Y7,3 Seasons,Kids' TV,Teen surfer Zak Storm is mysteriously transpor...,2018-09-13,2018.0,3,Seasons